### ISSUE TITLE
感谢大佬~求教一下salt和password的获取方法

### ISSUE THREAD

**Issue by Shirui816** [VergilGao/Telecom-IPTV-Mock#2]
希望您能指个方向，多谢

**Comment by Shirui816** [comment]
password 搞定了，但是authenticator算不对……直接用了您的方法，不知道是不是salt不对，因为不懂java，没能在apk里找到authenticator生成方法或者函数，麻烦大佬有空指点一下，多谢！

**Comment by VergilGao** [comment]
java 源码里面没有，要反汇编native包

**Comment by Shirui816** [comment]
多谢回复！我研究一下。

**Comment by sht2017** [comment]
> 多谢回复！我研究一下。

如果不会的话可以试试看抓包然后暴力跑出来 但是算法不一定一样
