### ISSUE TITLE
请问salt是默认的000000还是什么？

### ISSUE THREAD

**Issue by flylufly** [VergilGao/Telecom-IPTV-Mock#5]
请问salt是默认的000000还是什么？这个没有抓包到

**Comment by flylufly** [comment]
大佬，我也是长春的应该是一样的，请大佬告诉下这个SALT的值，万分感谢,或者大佬给个Q

**Comment by VergilGao** [comment]
salt需要你自己逆向机顶盒里的程序
一般在加密的.so里

**Comment by flylufly** [comment]
大佬的是多少，我试试大佬的，感谢~~~~~~~

**Comment by flylufly** [comment]
求大佬给下大佬的这六位数
