### ISSUE TITLE
请教SALT

### ISSUE THREAD

**Issue by flylufly** [VergilGao/Telecom-IPTV-Mock#6]
大佬 没暴力跑出来这个 盒子反编译获取权限太难了 请大佬给个您的SALT 我跟您是一个地区的 万分感谢

**Comment by flylufly** [comment]
还有个请教的问题就是IPTV密码，维护人员告诉的是IPTV账号后8位，对么 ，还是88888888

**Comment by VergilGao** [comment]
adb可以导出所有的apk
找iptv字样的apk，随便找个解包软件解包
然后先找java部分代码，没有的话再找so文件，so文件用ida反汇编，然后特征分析DES加密部分的方法块。

这种东西我建议你自己搞，搞不明白的话那就放弃吧。
